name: Core Module CI

on:
  push:
    paths:
      - 'packages/core/**'
      - 'spec/**'
      - '.github/workflows/ci-core.yml'
  pull_request:
    paths:
      - 'packages/core/**'
      - 'spec/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['18', '20']
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build core module
        run: pnpm build:core
      
      - name: Run tests
        run: pnpm test:core
      
      - name: Upload coverage
        if: matrix.os == 'ubuntu-latest' && matrix.node == '20'
        uses: codecov/codecov-action@v3
        with:
          directory: ./packages/core/coverage
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: core-build-${{ matrix.os }}-node${{ matrix.node }}
          path: packages/core/dist