name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Package ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x64
            os: ubuntu-latest
            build_args: "--linux AppImage deb rpm --x64 --publish never"
            artifact_glob: |
              release/*-linux-x64.AppImage
              release/*-linux-x64.deb
              release/*-linux-x64.rpm
          - name: macos-x64
            os: macos-13
            build_args: "--mac --x64 --publish never"
            artifact_glob: |
              release/*-mac-x64.dmg
              release/*-mac-x64.zip
          - name: macos-arm64
            os: macos-14
            build_args: "--mac --arm64 --publish never"
            artifact_glob: |
              release/*-mac-arm64.dmg
              release/*-mac-arm64.zip
          - name: windows-x86
            os: windows-latest
            build_args: "--win --ia32 --publish never"
            artifact_glob: |
              release/*-win-ia32.exe
          - name: windows-arm64
            os: windows-latest
            build_args: "--win --arm64 --publish never"
            artifact_glob: |
              release/*-win-arm64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application bundles
        run: npm run build:prod

      - name: Package ${{ matrix.name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npx electron-builder ${{ matrix.build_args }}

      - name: Upload packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.artifact_glob }}
          if-no-files-found: error

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download packaged artifacts
        uses: actions/download-artifact@v4
        with:
          path: release

      - name: List release payload
        run: ls -R release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: release/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
